version: "3.7"

services:
  jitsuOrchestrator:
    image: 627477209022.dkr.ecr.us-west-2.amazonaws.com/jitsuai/anyservice:jdbc-server-760c602830fe3aa5258c943f3fe1d1b8012eabd5
    container_name: jitsuOrchestrator
    restart: always
    depends_on:
      - jitsuServer
    environment:
      - JDBC_SERVER_TRANSPORT_MODE=http
      - JDBC_AUTH=PAM
      - CONTAINER_NAME=jitsuOrchestrator
      - JDBC_PORT=10000
      - DASHBOARD_PORT=8080
    ports: 
      - "10000:10000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock